Repository thiagopbueno/model-aware-policy-optimization, pull requests merged in 2019-08, with the labels that each got.

#75 feat: use observed samples when branching factor is 0
  mapo/agents/mapo/losses.py
  mapo/agents/mapo/mapo.py
Labels: enhancement

#76 test: skip exploration tests
  mapo/agents/mapo/tests/test_exploration_state.py
  mapo/agents/td3/tests/test_exploration_state.py
Labels: bug

#82 fix: maximize the actor objective
  mapo/agents/mapo/losses.py
Labels: bug

#83 Feature: add dynamics delay and reoder apply ops
  mapo/agents/mapo/mapo.py
  mapo/agents/mapo/mapo_policy.py
Labels: enhancement

#86 Feature/time awareness
  mapo/envs/__init__.py
  mapo/envs/navigation.py
  mapo/envs/tests/test_navigation.py
Labels: enhancement

#91 feat: add critic explained variance statistic
  mapo/agents/mapo/losses.py
Labels: enhancement

#90 fix: check obs type when branching factor is 0
  mapo/agents/mapo/losses.py
  mapo/tests/agents/mapo/test_losses.py
Labels: bug

#94 Feature/grad stats
  mapo/agents/mapo/mapo_policy.py
Labels: enhancement, help wanted
